### 2020년 3월 27일
# 연습문제
## Numpy 기초

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [22]:
l = [[0,1,2], [3,4,5], [6,7,8], [9,10,11]]
a = np.array(l)

In [23]:
display(a)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### 1.  type(a), len(a), len(a[0]) 을 확인하시오.

In [18]:
len(a), len(a[0])

(4, 3)

### 2. a.dtype, a.shape, a.ndim 을 확인하시오.

In [25]:
a.ndim

2

### 3. a[0], a[0,0], a[-1], a[-1,-1] 값을 확인하시오.

In [31]:
a[-1, -1]

11

### 4. a에서 1, 5, 6 값을 출력하시오.

In [33]:
a[1,2]

5

In [39]:
a2 = np.zeros([5,5])
a2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 5. a2 에서 두번째 행의 세번째 칼럼을 1로 바꾸시오.

In [40]:
a2[1, 2] = 1
a2

array([[0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 6. a2 에서 마지막 행의 값을 모두 2로 바꾸시오.

In [43]:
a2[4] = 2

In [44]:
a2

array([[0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2.]])

### 7. a2 에서 3번째와 4번째 칼럼을 모두 3으로 바꾸시오.

In [ ]:
'''
int i,j;

for(i=0;i<5;i++) {
    for(j=2:j<4;j++)
        a[i][j] = 3;
}
'''

In [49]:
#a2[:, 2] = 3
#a2[:, 3] = 3
a2[:, 2:4] = 3
a2

array([[0., 0., 3., 3., 0.],
       [0., 0., 3., 3., 0.],
       [0., 0., 3., 3., 0.],
       [0., 0., 3., 3., 0.],
       [2., 2., 3., 3., 2.]])

### 8. a2 의 값을 모두 더하시오.
- 어레이의 sum() 함수 사용

In [51]:
a2.sum()

36.0

In [52]:
a2.mean()

1.44

In [55]:
a2.std()

1.416474496770062

In [56]:
a3 = np.arange(10)
a3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 9. a3 의 모든 값을 2배로 만드시오.
- [0, 2, 4, ... , 18]

In [58]:
a3 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 10. a3 를 변형하여 [1, 2, 3,..., 10] 을 만드시오

In [59]:
a3+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 11. a3 를 2개의 행과 5개의 열이 되게 만드시오.
- a3.reshape() 함수 사용

In [62]:
a3.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
a4 = np.array([True, False, False, True, False])
b = np.array([1,2,3,4,5])
a4

array([ True, False, False,  True, False])

### 12. a4.sum() 값을 계산하고, True 의 갯수와 동일함을 확인하시오.

In [66]:
5 - a4.sum()

3

### 13. a4*b 의 값을 계산하시오.

In [67]:
a4*b

array([1, 0, 0, 4, 0])

In [68]:
a5 = np.array([-1,2,-3,4,-5])
a5

array([-1,  2, -3,  4, -5])

### 14. a5<0 의 결과를 확인하시오.

In [69]:
a5<0

array([ True, False,  True, False,  True])

In [70]:
(a5<0)*a5

array([-1,  0, -3,  0, -5])

### 15. 1-(a5<0) 의 결과를 확인하시오.

In [71]:
1 - (a5<0)

array([0, 1, 0, 1, 0])

### 16. np.random 에 있는 rand(), randn(), randint, normal() 함수의 차이를 설명하시오.

In [75]:
np.random.randn(10)

array([-0.30597691,  1.50486456, -2.14231718,  0.08960382, -0.7172506 ,
       -0.93719486, -1.26287294,  0.58192656, -0.38386833, -0.8498842 ])

### 17. np.random.randn(100) 의 결과를 해석하시오.

In [76]:
np.random.randn(100)

array([ 1.93024422,  1.66798154, -1.59603892, -1.84043756,  1.22966797,
       -0.60817365,  0.09945466, -0.62561502,  0.03472626,  0.87041586,
        1.49426849, -0.21789475, -1.19190694,  0.0536578 , -1.05231686,
        0.39159728,  0.13165821, -0.21881361, -0.76825357, -0.8684201 ,
       -0.278667  , -0.25632483, -1.10174573,  0.14516695, -0.07955492,
        1.30310231,  1.52339963,  0.25799766, -0.64065981,  1.14990786,
       -0.89608093, -0.3758691 , -1.90561482,  0.16766104, -0.62728619,
        0.84271742,  0.70600115, -0.44652317,  1.22603248, -2.72764073,
       -1.32126353,  0.2806065 ,  0.7142715 , -2.31217663, -0.85772058,
       -0.40284162,  1.27682531,  1.6441123 , -0.48753932, -0.7422244 ,
       -0.34855204,  0.41679125, -3.05298643,  0.4291127 ,  0.42898293,
       -0.49367895,  0.30547945,  0.65072836, -1.66119692,  0.84264025,
       -0.84918376,  0.87943476,  0.67448521, -0.52552401, -0.22956984,
       -1.48887682, -1.2012286 , -0.43237775,  0.33769902,  1.01

In [91]:
(np.random.randn(100)==0).sum()

0

### 18. 주사위를 100번 던지고, 1이나 6이 나온 횟수를 구하시오.
- np.random.randint() 사용
- (a==1).sum() 과 같이 적용

In [312]:
dice = np.random.randint(1,7, size=100)
dice

array([5, 1, 6, 3, 5, 1, 5, 3, 4, 5, 5, 6, 4, 3, 2, 5, 6, 6, 6, 4, 4, 2,
       1, 1, 6, 5, 6, 2, 4, 4, 5, 4, 3, 2, 2, 3, 3, 6, 4, 3, 5, 1, 5, 4,
       1, 5, 5, 4, 5, 5, 5, 3, 3, 5, 1, 2, 2, 3, 1, 2, 6, 4, 2, 2, 1, 1,
       1, 5, 5, 1, 2, 1, 1, 2, 1, 2, 2, 6, 6, 3, 6, 5, 6, 1, 6, 2, 2, 3,
       6, 4, 3, 4, 4, 4, 2, 5, 6, 1, 2, 1])

In [314]:
dice==1

array([False,  True, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False,  True, False, False, False, False,
       False,  True,  True,  True, False, False,  True, False,  True,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
        True])

In [315]:
(dice==1).sum()

18

In [316]:
(dice==6).sum()

16

In [319]:
card = np.random.randint(13*4, size=[3,4])
card

array([[24, 30, 14, 45],
       [ 5, 25, 43,  9],
       [11, 34, 27, 37]])

In [322]:
display(card//13, card%13)

array([[1, 2, 1, 3],
       [0, 1, 3, 0],
       [0, 2, 2, 2]], dtype=int32)

array([[11,  4,  1,  6],
       [ 5, 12,  4,  9],
       [11,  8,  1, 11]], dtype=int32)

### 19. 아래의 결과를 분석하시오.

In [326]:
a6 = np.zeros([10,10])
a6

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [327]:
a6[1::2] = 1
a6

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [328]:
a6[:, 1::2] = 1
a6

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 20. np.eye(9) 을 응용하여 역대각선 행렬을 구하시오.
- 추가로, 아래와 같은 X 자 행렬도 구하시오.

In [330]:
a = np.eye(9)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [331]:
l = [3,2,1,5]
l[::-1]

[5, 1, 2, 3]

In [332]:
a[::-1]

array([[0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [333]:
a[:, ::-1]

array([[0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [334]:
a + a[::-1]

array([[1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.]])